language: python

sudo: false

env:
    - CONDA="python=2.7"
    #- CONDA="python=3.4"

before_install:
    - wget http://bit.ly/miniconda -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda update --yes conda
    - conda config --add channels ioos -f
    - travis_retry conda create --yes -n test --file conda_requirements.txt $CONDA
    - source activate test
    - travis_retry pip install
    # GUI
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"

script:
    - python setup.py test
