language: python
python:
  - "2.7"
  - "3.3"
# Setup Anaconda.
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-2.2.2-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/anaconda/bin:$PATH
  # Update conda itself.
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda.
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
install:
  - conda create --yes -n env_name python=$TRAVIS_PYTHON_VERSION pip numpy scipy matplotlib pandas netCDF4 Shapely nose
  - source activate env_name
  # Not in anaconda.
  - pip install gsw
  - pip install seawater
  - python setup.py install
script:
  - cd oceans/tests && nosetests --verbose --nocapture
