language: python
python:
  - "2.7"
  - "3.3"

virtualenv:
  system_site_packages: true

before_install:
  - ci/before_install.sh

install:
  - pip install -r requirements.txt
  - python setup.py install

script:
  - cd oceans/tests
  - nosetests --verbose --nocapture

branches:
  only:
    - master
