language: python
python:
  - "2.7"
  - "3.3"

virtualenv:
  system_site_packages: true

before_install:
  - ci/before_install.sh

install:
  - pip install --use-mirrors numpy
#   - pip install --use-mirrors scipy
  - pip install --use-mirrors matplotlib
  - pip install --use-mirrors netCDF4
  - pip install --use-mirrors gsw
  - python setup.py install

script:
  - cd oceans/tests
  - nosetests --verbose --nocapture

branches:
  only:
    - master
