language: minimal

sudo: false

matrix:
  fast_finish: true
  include:
  - name: default
    env: TEST_TARGET=default PY=3.7
  - python: coding_standards
    env: TEST_TARGET=coding_standards PY=3.7

before_install:
  - wget http://bit.ly/miniconda -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
  - conda update conda
  - conda config --remove channels defaults --force
  - conda config --add channels conda-forge --force
  - conda create --name TEST python=$PY --file requirements.txt --file requirements-dev.txt
  - source activate TEST
  # GUI tests.
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  # Test source distribution.
  - python setup.py sdist && version=$(python setup.py --version) && pushd dist  && pip install oceans-${version}.tar.gz && popd

script:
    - if [[ $TEST_TARGET == 'default' ]]; then
        pytest -vv oceans --doctest-modules ;
      fi

    - if [[ $TEST_TARGET == 'coding_standards' ]]; then
        flake8 --max-line-length=105 oceans --exclude=_version.py ;
      fi
