language: python
python:
  - "2.7"
  - "3.3"

virtualenv:
  system_site_packages: true

before_install:
  - ci/before_install.sh
  - pip install --use-mirrors matplotlib pandas gsw netCDF4
install:
  - python setup.py install

script:
  - cd tests
#  - nosetests --verbose --nocapture

branches:
  only:
    - master
